name: npm-publish
run-name: NPM Publish
on:
  push:
    branches:
      - "main"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
